name: 'Interactive play to debug environment'
cmd: 'interactive_play'
env:
  # Small set of generated levels
  name: sokoban
  n_max_episode_steps: 200
  levels: src/environments/sokoban/levels/gen_8x8_1000_levels__sol_10.txt
  maxsize: 8,8
  randomize: true  # randomly rotate and shift level

  #### Download levels from: https://github.com/google-deepmind/boxoban-levels
  # name: boxoban
  # n_max_episode_steps: 200
  # # levels: /home/excellent/ds/others/boxoban-levels/medium/valid
  # # levels: /home/excellent/ds/others/boxoban-levels/hard
  # # levels: /home/excellent/ds/others/boxoban-levels/unfiltered/train
  # # levels: /home/excellent/ds/others/boxoban-levels/unfiltered/valid
  # # levels: /home/excellent/ds/others/boxoban-levels/unfiltered/test
  # # levels: /home/excellent/ds/others/boxoban-levels/unfiltered/valid
  # # levels: /home/excellent/ds/others/boxoban-levels/unfiltered/valid/000.txt

infra:
  device: gpu
  log: mem